---
title: "Group_05_Analysis"
format: 
  html:
    embed-resources: true
    code-tools: true
  pdf: default
editor: visual
execute:
  warning: false
  message: false
output:
  pdf_document
---

```{r}
library(tidyverse)
library(moderndive)
library(gapminder)
library(sjPlot)
library(stats)
library(jtools)
library(skimr)
library(GGally)
library(MASS)
library(dplyr)
library(knitr)
library(gridExtra)
library(kableExtra)
```

# Data wrangling

```{r}
data5 <-  read.csv('dataset05.csv')
data5$Region <- as.factor(data5$Region)
data5$Household.Head.Sex <- as.factor(data5$Household.Head.Sex)
data5$Type.of.Household <- as.factor(data5$Type.of.Household)
data5$Electricity <- as.factor(data5$Electricity)

```

# Exploration of data

```{r}
skim(data5)
```

# Data visualization

```{r}
data <- data5%>%
  mutate(log.Total.Household.Income=log(Total.Household.Income))%>%
  mutate(log.Total.Food.Expenditure=log(Total.Food.Expenditure))%>%
  mutate(log.House.Floor.Area=log(House.Floor.Area))%>%
  mutate(log.Household.Head.Age=log(Household.Head.Age))%>%
  mutate(log.House.Age=log(House.Age+0.1))%>%
  mutate(log.Number.of.bedrooms=log(Number.of.bedrooms+0.1))%>%
  dplyr::select(Total.Number.of.Family.members,
         log.Total.Household.Income,
         log.Total.Food.Expenditure,
         log.House.Floor.Area,
         Household.Head.Sex,
         log.Household.Head.Age,
         Type.of.Household,
         log.House.Age,
         log.Number.of.bedrooms,Electricity)

ggpairs(data,upper=list(continuous=wrap("points", alpha=0.4, color="#d73027")),
lower="blank", axisLabels="none")
```
